import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../", import.meta.url);

test("character generator contains the printable flow and SWADE safeguards", async () => {
  const [page, css, layout, pagesConfig, staticIndex] = await Promise.all([
    readFile(new URL("app/page.tsx", root), "utf8"),
    readFile(new URL("app/globals.css", root), "utf8"),
    readFile(new URL("app/layout.tsx", root), "utf8"),
    readFile(new URL("vite.pages.config.ts", root), "utf8"),
    readFile(new URL("index.html", root), "utf8"),
  ]);

  assert.match(layout, /lang="ru"/);
  assert.match(layout, /Лист персонажа Ultima Forsan/);
  assert.match(layout, /hydra-favicon-white\.svg/);
  assert.match(pagesConfig, /base: "\/bonesandink\/"/);
  assert.match(staticIndex, /hydra-favicon-white\.svg/);
  assert.match(page, /window\.print\(\)/);
  assert.match(page, /localStorage/);
  assert.match(page, /ultima-forsan-heroes-v2/);
  assert.match(page, /LEGACY_STORAGE_KEY/);
  assert.match(page, /function makeHeroRecord/);
  assert.match(page, /const duplicateHero/);
  assert.match(page, /duplicatedCharacter\.creationLocked = false/);
  assert.match(page, /Мои герои/);
  assert.match(page, /Сохранено автоматически/);
  assert.match(page, /SWADE для кампании/);
  assert.match(page, /const skillBudget = 12/);
  assert.match(page, /className="skill-attribute"/);
  assert.match(page, /name: skill\.name,[\s\S]*attribute: skill\.attribute/);
  assert.doesNotMatch(page, /Книга Ultima Forsan/);
  assert.match(page, /const SWADE_ADAPTATIONS/);
  assert.match(page, /const LEGACY_SKILL_TARGETS/);
  assert.match(page, /migratedLevels/);
  assert.match(page, /name: "Сыщик", note: "\+2 к Поиску информации/);
  assert.match(page, /Маскировка", "Скрытность/);
  assert.match(page, /Лазание · Метание · Плавание", "Атлетика/);
  assert.match(page, /Расследование", "Поиск информации/);
  assert.match(page, /Уличное чутьё \(навык\)", "«Уличное чутьё»; при требовании — черта/);
  assert.match(page, /const CAMPAIGN_UNAVAILABLE_EDGE_NAMES/);
  assert.match(page, /function edgeAvailableInCampaign/);
  assert.match(page, /function campaignEdgeIssue/);
  assert.match(page, /Сардоническая усмешка/);
  assert.match(page, /Черта выдаётся только после заражения в игре/);
  assert.match(page, /Черта недоступна в кампании Ultima Forsan/);
  assert.match(page, /id: "weird-science", name: "Безумная наука"/);
  assert.match(page, /id: "witchcraft", name: "Ведьмовство", attribute: "spirit"/);
  assert.match(page, /name: "Мистический дар \(безумная наука\)"/);
  assert.match(page, /Искариот"[\s\S]*Скрытность d8\+/);
  assert.doesNotMatch(page, /Маскировка d8\+", detail/);
  assert.match(page, /Тевтонский инквизитор"[\s\S]*Уличное чутьё,[\s\S]*Поиск информации d6\+/);
  assert.match(page, /Даёт черту «Сыщик»|Бесплатно даёт черту «Сыщик»/);
  assert.match(page, /Атлетике \(плавание\)/);
  assert.match(page, /const baseEdgeSlots = 1/);
  assert.match(page, /className="adaptation-guide"/);
  assert.match(css, /\.adaptation-guide/);
  assert.match(page, /const EDGE_GUIDES: TraitGuide\[\]/);
  assert.match(page, /const HINDRANCE_GUIDES: TraitGuide\[\]/);
  assert.match(page, /function traitGuideDetail/);
  assert.match(page, /minorDetail:/);
  assert.match(page, /majorDetail:/);
  assert.match(page, /generatedNotes\.includes\(entry\.note\)/);
  assert.match(page, /restoredHindrances/);
  assert.match(page, /disabled=\{Boolean\(fixedSeverity\)\}/);
  assert.match(page, /Тяжесть изъяна задана правилами/);
  assert.match(page, /namedGuide && namedGuide\.severity !== "either"/);
  assert.match(page, /function TraitGuideInput/);
  assert.match(page, /disableFutureRank/);
  assert.match(page, /className="advance-edge-picker"/);
  assert.match(page, /excludeNames=\{character\.edges\.filter/);
  assert.match(page, /function AttributeDie/);
  assert.match(page, /const ATTRIBUTE_DICE: Die\[\] = \[4, 6, 8, 10, 12\]/);
  assert.match(page, /className="blood-stat"/);
  assert.doesNotMatch(page, /className="blood-note"/);
  assert.match(page, /className="sheet-section skills-print first-page-skills"/);
  assert.match(page, /className="sheet-section weapons-section second-page-weapons"/);
  assert.match(page, /className="appearance-print second-page-appearance"/);
  assert.match(page, /edgeAdvances/);
  assert.match(page, /const hindranceEdgeSlots = Math\.floor\(creditedHindrancePoints \/ 2\)/);
  assert.match(page, /const edgeLimit = baseEdgeSlots \+ hindranceEdgeSlots \+ edgeAdvances/);
  assert.match(page, /Получить повышение/);
  assert.match(page, /const applyAdvance/);
  assert.match(page, /role="dialog"/);
  assert.match(page, /Новая черта/);
  assert.match(page, /Повысить навыки/);
  assert.match(page, /Устранить изъян/);
  assert.match(page, /skillAdvancePoints/);
  assert.match(page, /attributeRaiseRanks/);
  assert.match(page, /function rankFromAdvances/);
  assert.match(page, /advances >= 16/);
  assert.match(page, /advances >= 12/);
  assert.match(page, /advances >= 8/);
  assert.match(page, /advances >= 4/);
  assert.match(page, /следующий ранг с/i);
  assert.doesNotMatch(page, /value=\{character\.rank\}/);
  assert.match(page, /function requiredRank/);
  assert.match(page, /\.split\(",", 1\)/);
  assert.match(page, /rankAllows/);
  assert.match(page, /Текущий ранг/);
  assert.match(page, /В справочнике/);
  assert.match(page, /Путь Лимба/);
  assert.match(page, /Верные спутники/);
  assert.match(page, /Устойчивость к мистическим силам\+/);
  assert.match(page, /Упреждающий удар\+/);
  assert.match(page, /Управление потоком/);
  assert.match(page, /Адаптация SWADE: старые навыки/);
  assert.match(page, /Начните вводить черту/);
  assert.match(page, /const WEAPON_GUIDES: WeaponGuide\[\]/);
  assert.match(page, /function WeaponGuideInput/);
  assert.match(page, /Справочник вооружения/);
  assert.match(page, /Варианты оружия Ultima Forsan/);
  assert.match(page, /Дробовой пистоль/);
  assert.match(page, /Боевой заступ/);
  assert.match(page, /weapon-guide-hint/);
  assert.match(page, /function preparePortrait/);
  assert.match(page, /accept="image\/jpeg,image\/png,image\/webp"/);
  assert.match(page, /Загрузить портрет/);
  assert.match(page, /className="sheet-header-portrait"/);
  assert.doesNotMatch(page, /className="sheet-seal"/);
  assert.match(page, /canvas\.toDataURL\("image\/jpeg"/);
  assert.match(page, /type AdvanceRecord/);
  assert.match(page, /function captureAdvanceState/);
  assert.match(page, /const undoLastAdvance/);
  assert.match(page, /Журнал развития/);
  assert.match(page, /Отменить последнее/);
  assert.match(page, /const exportHero/);
  assert.match(page, /const importHero/);
  assert.match(page, /ultima-forsan-hero/);
  assert.match(page, /const EQUIPMENT_GUIDES: EquipmentGuide\[\]/);
  assert.match(page, /type ArmorArea = "head" \| "torso" \| "arms" \| "legs"/);
  assert.match(page, /areas: \["head", "torso", "arms", "legs"\]/);
  assert.match(page, /const effectiveArmor = Math\.max\(torsoArmor, manualTorsoArmor\)/);
  assert.match(page, /Броня по зонам/);
  assert.match(page, /Как считается броня/);
  assert.match(page, /Броня торса вручную/);
  assert.match(page, /rangedArmor: 2/);
  assert.match(page, /const purchaseEquipment/);
  assert.match(page, /Нагрузка/);
  assert.match(page, /function edgeRequirementIssues/);
  assert.match(page, /creationLocked/);
  assert.match(page, /Зафиксировать героя/);
  assert.ok(page.indexOf("Зафиксировать героя") > page.indexOf('className="form-footer"'));
  assert.match(page, /className="play-dashboard"/);
  assert.match(page, /<span>Флорины<\/span><strong>\{character\.florins \|\| 0\}<\/strong><small>наличные<\/small>/);
  assert.match(page, /"play-workspace"/);
  assert.match(page, /const playSkills = skills\.filter\(\(skill\) => skill\.level > 0\)/);
  assert.match(page, /Только изученные/);
  assert.match(page, /Изменить досье/);
  assert.match(page, /Управлять снаряжением/);
  assert.match(page, /Состояние в игре/);
  assert.match(page, /Потраченный боезапас/);
  assert.match(page, /Настройки PDF/);
  assert.match(page, /type ArcaneTradition = "alchemy" \| "witchcraft" \| "weird-science"/);
  assert.match(page, /const ARCANE_TRADITIONS/);
  assert.match(page, /const POWER_GUIDES: PowerGuide\[\]/);
  assert.match(page, /Без пунктов силы/);
  assert.match(page, /function rollExplodingDie/);
  assert.match(page, /const activatePower/);
  assert.match(page, /recipeCost/);
  assert.match(page, /const setPreparedPowerQuantity/);
  assert.match(page, /florins: String\(florins - difference \* recipeCost\)/);
  assert.match(page, /Приготовление сразу меняет остаток флоринов/);
  assert.match(page, /приготовить за/);
  assert.match(page, /Устройство сломано/);
  assert.match(page, /witchcraftBacklash/);
  assert.match(page, /legacyName: "Ночное зрение"/);
  assert.match(page, /legacyName: "Кукла"/);
  assert.match(page, /legacyName: "Волна"/);
  assert.match(page, /className="sheet-section magic-print"/);
  assert.match(page, /Мистика, рецепты и устройства/);
  assert.match(page, /className="magic-print-grid"/);
  assert.match(page, /function SheetOrnaments/);
  assert.match(page, /className="renaissance-frame"/);
  assert.match(page, /printExtraNotesPage/);
  assert.match(page, /portraitZoom/);
  assert.match(page, /const WEAPON_PURCHASE_DATA/);
  assert.match(page, /const purchaseWeapon/);
  assert.match(css, /@page \{ size: A4 portrait; margin: 0; \}/);
  assert.match(css, /@media print/);
  assert.match(css, /print-color-adjust: economy/);
  assert.match(css, /\.character-sheet \{[\s\S]*background: #fff !important;/);
  assert.match(css, /background-image: none !important/);
  assert.match(page, /<svg viewBox="0 0 32 32"/);
  assert.match(page, /className="die-svg-face"/);
  assert.match(page, /className="die-svg-facet"/);
  assert.match(css, /\.die-svg-face/);
  assert.match(css, /\.attribute-die\.is-current \.die-svg-face/);
  assert.match(css, /\.hide-die-values \.die-svg-value/);
  assert.match(css, /\.big-stat-row \.blood-stat/);
  assert.match(css, /\.first-page-skills/);
  assert.match(css, /\.second-page-weapons/);
  assert.match(css, /\.edge-budget-note/);
  assert.match(css, /\.rank-display/);
  assert.match(css, /\.advance-modal/);
  assert.match(css, /\.advance-types/);
  assert.match(css, /\.advance-edge-picker/);
  assert.match(css, /\.weapon-guide-menu/);
  assert.match(css, /\.weapon-guide-hint/);
  assert.match(css, /\.portrait-uploader/);
  assert.match(css, /\.sheet-header-portrait/);
  assert.match(css, /filter: grayscale\(1\)/);
  assert.match(css, /\.advance-history/);
  assert.match(css, /\.hero-import-input/);
  assert.match(css, /\.equipment-catalog/);
  assert.match(page, /const setEquipmentQuantity/);
  assert.match(page, /equipment-card-select/);
  assert.match(page, /equipment-quantity/);
  assert.match(css, /\.equipment-card\.is-selected/);
  assert.match(css, /\.equipment-rules-note/);
  assert.match(css, /\.equipment-card-select:focus-visible/);
  assert.match(css, /\.creation-lock/);
  assert.match(css, /\.play-dashboard/);
  assert.match(css, /\.play-skills-grid/);
  assert.match(css, /\.play-power-list/);
  assert.match(css, /\.magic-rules-intro/);
  assert.match(css, /\.magic-print/);
  assert.match(css, /\.magic-tradition-strip/);
  assert.match(css, /\.renaissance-frame/);
  assert.match(css, /\.frame-fleuron/);
  assert.match(page, /hydra-logo-full-black\.svg/);
  assert.match(css, /\.site-logo img/);
  assert.match(page, /function PlayNumberStepper/);
  assert.doesNotMatch(page, /shooting: 6/);
  assert.match(page, /stepper-up/);
  assert.match(page, /stepper-down/);
  assert.match(css, /\.play-number-controls button::before/);
  assert.match(css, /\.split-entries > div \{ min-width: 0;/);
  assert.match(css, /@container form-panel \(min-width: 780px\)/);
  assert.match(css, /\.state-grid/);
  assert.match(css, /\.notes-page/);
  assert.doesNotMatch(page, /_sites-preview|react-loading-skeleton|codex-preview/);
});
